core: add missing header inclusion
Otherwise throwing the following error:
lib/core.c:102:9: error: implicit declaration of function 'basename' is
invalid in C99

Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>